services:
  entigraph:
    build: .
    image: entigraph_image:latest
    container_name: entigraph_container
    env_file:
      - .env
    volumes:
      - ./data:/app/data

# 単一サービスの設定では厳密には必要ありませんが、ネットワークを定義することは良い習慣です。
networks:
  default:
    driver: bridge
